instrumentkit/InstrumentKit

instruments/instruments/abstract_instruments/comm/visawrapper.py
instruments/instruments/abstract_instruments/instrument.py

adapt open_visa()

---

.coveragerc
.travis.yml
README.md

Trello card: https://trello.com/c/SfjQFPYb/7-setup-coveralls-io-service

Card 7 > Setup coveralls.io service

---

instruments/instruments/tests/test_util_fns.py
instruments/instruments/util_fns.py

Trello link: https://trello.com/c/WIER9G91/5-split-unit-str-unable-to-handle-numbers-in-exponential-form

Card 5 > util_fns > Fixed split_unit_str to handle E notation

---

instruments/instruments/agilent/agilent33220a.py
instruments/instruments/agilent/agilent34410a.py
instruments/instruments/generic_scpi/__init__.py
instruments/instruments/generic_scpi/scpi_function_generator.py
instruments/instruments/generic_scpi/scpi_instrument.py
instruments/instruments/generic_scpi/scpi_multimeter.py
instruments/instruments/lakeshore/lakeshore340.py
instruments/instruments/lakeshore/lakeshore370.py
instruments/instruments/lakeshore/lakeshore475.py

Pass pylint on generic scpi files. A few TODOs have been ignored because they won't be addressed until I can test what the actual instrument behaviour is suppose to be.

Lint generic scpi

---

instruments/.pylintrc
instruments/instruments/newport/__init__.py
instruments/instruments/newport/errors.py
instruments/instruments/newport/newportesp301.py
instruments/instruments/tests/test_newport/test_newportesp301.py

Ok, so this one was a pain in the bum. Its a pretty complex piece of equipment, but I managed to get rid of some of the todos, but the esp 301 is going to need some more work in the future. There's a few things that I noticed (like how when `_execute_immediately` is `False` I don't think the results are ever returned, see how `_bulk_query_resp` is never returned) that'll need to be looked at in the future.
Also, making unit tests for this at some point is going to be super fun. For now I've made the test file to encourage tests being added by those working in the esp301 code base in the future.

Lint newport

---

instruments/instruments/oxford/__init__.py
instruments/instruments/oxford/oxforditc503.py
instruments/instruments/tests/test_oxford/test_oxforditc503.py

Well compared to Newport this took no time at all.

Lint oxford

---

instruments/instruments/phasematrix/__init__.py
instruments/instruments/phasematrix/phasematrix_fsw0020.py
instruments/instruments/tests/test_phasematrix/test_phasematrix_fsw0020.py

Tests and linting for the phasematrix fsw0020
A todo in the file reminds me that we should write a `W` to `dBm` converter in `instruments.units` at some point. I'll make an issue for that.

Lint phasematrix

---

instruments/instruments/picowatt/__init__.py
instruments/instruments/picowatt/picowattavs47.py
instruments/instruments/tests/test_picowatt/test_picowatt_avs47.py

Nothing special; just lint and tests. Includes a small bug fix for getting the `input_source`

Lint picowatt

---

instruments/instruments/qubitekk/__init__.py
instruments/instruments/qubitekk/cc1.py

Keeping this to a minimum because there is a bunch of open work still for the qubitekk.

Linting for qubitekk

---

instruments/instruments/abstract_instruments/oscilloscope.py
instruments/instruments/rigol/__init__.py
instruments/instruments/rigol/rigolds1000.py

Rigol is in an unfortunate situation here. None of us have any Rigol equipment to test again, but its a very popular brand among hobbyists. This isn't anywhere close to done, nor do I know which parts are correct to write tests against.

Lint rigol

---

instruments/.pylintrc
instruments/doc/source/apiref/tektronix.rst
instruments/instruments/abstract_instruments/oscilloscope.py
instruments/instruments/tektronix/__init__.py
instruments/instruments/tektronix/tekawg2000.py
instruments/instruments/tektronix/tekdpo4104.py
instruments/instruments/tektronix/tekdpo70000.py
instruments/instruments/tektronix/tektds224.py
instruments/instruments/tektronix/tektds5xx.py

Linted all tektronix files and modified the AWG2000 file to use inner channel classes rather than outer for consistency. I still have to do that for all of them, but hey progress is progress.

Lint tektronix

---

instruments/.pylintrc
instruments/instruments/thorlabs/__init__.py
instruments/instruments/thorlabs/_abstract.py
instruments/instruments/thorlabs/_cmds.py
instruments/instruments/thorlabs/_packets.py
instruments/instruments/thorlabs/lcc25.py
instruments/instruments/thorlabs/pm100usb.py
instruments/instruments/thorlabs/sc10.py
instruments/instruments/thorlabs/tc200.py
instruments/instruments/thorlabs/thorlabsapt.py

No new unit tests this time, but I did add some properties to `ThorLabsPacket` to expose all its various internal properties.

Lint thorlabs

---

.travis.yml
instruments/.pylintrc
instruments/instruments/__init__.py
instruments/instruments/abstract_instruments/electrometer.py
instruments/instruments/abstract_instruments/multimeter.py
instruments/instruments/generic_scpi/scpi_instrument.py
instruments/instruments/other/__init__.py
instruments/instruments/rigol/rigolds1000.py
instruments/instruments/tektronix/tekdpo4104.py
instruments/instruments/tektronix/tekdpo70000.py
instruments/instruments/tektronix/tektds5xx.py
instruments/instruments/tests/test_util_fns.py
instruments/instruments/toptica/__init__.py

The final linting step! We finally made it! :tada: 
Oddly enough once I added `pylint` to travis here, I found that it was catching a few lines that it was not on my local machine. They were legit failures, but I couldn't figure out why it was being missed on my machine. Oh well, they've been fixed and all is good now.
Also, I had to disable to duplicate code checker entirely for now. I couldn't get it to disable for specific files (namely `multimeter.py` and `electrometer.py`) so its off if I some day figure that out.

Lint project

---

doc/source/acknowledgements.rst
doc/source/apiref/agilent.rst
doc/source/apiref/holzworth.rst
doc/source/apiref/hp.rst
doc/source/apiref/keithley.rst
doc/source/apiref/lakeshore.rst
doc/source/apiref/newport.rst
doc/source/apiref/oxford.rst
doc/source/apiref/phasematrix.rst
doc/source/apiref/picowatt.rst
doc/source/apiref/qubitekk.rst
doc/source/apiref/rigol.rst
doc/source/apiref/srs.rst
doc/source/apiref/tektronix.rst
doc/source/apiref/thorlabs.rst
doc/source/apiref/toptica.rst
doc/source/apiref/yokogawa.rst
doc/source/devguide/code_style.rst
doc/source/devguide/design_philosophy.rst
doc/source/devguide/index.rst
doc/source/devguide/testing.rst
doc/source/devguide/util_fns.rst
doc/source/index.rst
doc/source/intro.rst
instruments/util_fns.py

General documentation improvements, biggest is the extra examples for how to use the property factories

Doc improvements

---

instruments/__init__.py
instruments/abstract_instruments/instrument.py

This fixes the version string checking for `pyvisa` which should fix issue #110

Pyvisa version check fix

---

doc/examples/ex_qubitekk_gui.py
instruments/qubitekk/cc1.py
instruments/tests/test_qubitekk/test_qubitekk_cc1.py

I've decided to add a repeat-back ack message to the CC1 firmware. Works with newer and older versions of the firmware.

Cc1 adding ack

---

instruments/__init__.py

- Includes additional unit tests for `Instrument`
- Minor changes to the `CC1` class to handle new ACK functionality

Bump version 0.0.4 -> 0.0.5

---

instruments/phasematrix/__init__.py
instruments/picowatt/__init__.py
instruments/yokogawa/__init__.py

@scasagrande , this PR fixes the PEP3000 issues on the develop branch that are preventing the develop branch build from succeeding.

adding fixed newlines on init files

---

doc/examples/qubitekk/ex_qubitekk_mc1.py
doc/source/apiref/ondax.rst
doc/source/apiref/qubitekk.rst
instruments/ondax/__init__.py
instruments/ondax/lm.py
instruments/qubitekk/__init__.py
instruments/qubitekk/mc1.py
instruments/tests/test_ondax/test_lm.py
instruments/tests/test_qubitekk/test_qubitekk_mc1.py

Merge development branch into master.
This merges in PRs #144 and #145, which add the Ondax LM1 and Qubitekk MC1 drivers.

v0.3 Feature Set PR

---

instruments/__init__.py

- Includes fix for `pyvisa` version checking

Bump version 0.3.0 -> 0.3.1

---

doc/source/conf.py
doc/source/intro.rst
instruments/__init__.py
license/AUTHOR.TXT

A few quick and easy doc updates:
- Move `pyvisa` to being listed as required in the compiled documentation
- Update authorship & copyright years -> 2019

Doc updates

---

setup.py

Changes
----------
- Fixes `setup.py` for publishing to pypi

Fix setup.py for publishing

---

instruments/minghe/mhs5200a.py

Changes
----------
- A few docstring updates for the `MHS5200a` that I missed.

Docstring modifications

---

doc/source/apiref/yokogawa.rst
instruments/abstract_instruments/__init__.py
instruments/abstract_instruments/optical_spectrum_analyzer.py
instruments/tests/test_yokogawa/test_yokogawa_6370.py
instruments/yokogawa/__init__.py
instruments/yokogawa/yokogawa6370.py
setup.py

This PR is taking over from #187, having been refreshed and rebased.
Special thanks to @timhellwig for opening the original PR.
Changes
------------
- Adds an OpticalSpectrumAnalyzer base class
- Adds a Yokogawa6370 multichannel OSA

Optical spectrum analyzers

---

doc/source/conf.py
instruments/__init__.py
license/AUTHOR.TXT

Getting ready for the last Py2 release

Update copyrights for 2020

---

instruments/tests/test_thorlabs/test_thorlabs_apt.py
instruments/thorlabs/thorlabsapt.py

Extended test suite for full coverage.
**Bug fixes in `thorlabsapt.py`**:
- turn tuple into list before doing list operations
- make sure that `expect_data_len` is always provided for `querypacket`
routine. Data lengths taken from manual.
- Fixed typos

Full coverage tests and BFs for Thorlabs APT

---

instruments/tests/test_agilent/test_agilent_33220a.py

Added a couple of tests for error messages and edge cases.
Can also see if that webhook travis is better now :smiley:

Full coverage for Agilent 33220a tests

---

instruments/glassman/glassmanfr.py
instruments/tests/test_glassman/test_glassmanfr.py

Completed tests for Glassman FR for full coverage.
Fixed a few typos & docstring in the main class.

GlassmanFR Tests and Typo fixes

---

instruments/tests/test_minghe/test_minghe_mhs5200a.py

Just a couple more tests for MHS5200a

Full coverage tests for Minghe MHS5200a

---

instruments/tests/test_keithley/test_keithley2182.py
instruments/tests/test_keithley/test_keithley6220.py

Added and extended existing tests for these two instruments. Mostly minor things here.

Full coverage for Keithley 2182 & 6220

---

.travis.yml
README.rst
setup.py
tox.ini

Adds support for Python 3.9, with testing under CPython 3.9
Issue #276

Add support for CPython 3.9

---

instruments/tests/test_phasematrix/test_phasematrix_fsw0020.py

Adding tests for functions that are not implemented to get to full coverage

Full coverage test suite for Phasematrix FSW 0020

---

instruments/tests/test_fluke/test_fluke3000.py
instruments/tests/test_phasematrix/test_phasematrix_fsw0020.py

Final test for Fluke3000, somehow I missed a line in PR #269. This test should now fully cover the Fluke 3000.

Test for full coverage of Fluke3000

---

.github/workflows/test.yml

Coveralls report is here: https://coveralls.io/builds/45805380
Looks like everything passes w/o any issues up to here :)

Rename "finish" to "coverage"

---

.pre-commit-config.yaml
doc/examples/ex_hp3456.py
instruments/newport/newport_pmc8742.py
instruments/newport/newportesp301.py
instruments/rigol/rigolds1000.py
instruments/srs/srs830.py
instruments/tektronix/tekawg2000.py
instruments/tektronix/tekdpo70000.py
instruments/tests/test_hp/test_hp3456a.py
instruments/tests/test_newport/test_newport_pmc8742.py
instruments/tests/test_newport/test_newportesp301.py
instruments/tests/test_tektronix/test_tekawg2000.py
instruments/tests/test_tektronix/test_tekdpo70000.py
instruments/tests/test_thorlabs/test_thorlabs_apt.py
instruments/thorlabs/thorlabsapt.py

I had to upgrade many repos today because of https://github.com/psf/black/issues/2964

Update pre-commit hooks

---

src/instruments/tektronix/tekdpo4104.py
src/instruments/tektronix/tektds224.py
src/instruments/tektronix/tektds5xx.py
src/instruments/teledyne/maui.py
tests/test_tektronix/test_tekdpo4104.py
tests/test_test_utils.py

Some tests were generating errors in the case with numpy installed.
This fixes all of those errors
fyi @trappitsch

Fix warnings with numpy enabled

---

src/instruments/thorlabs/_abstract.py
tests/test_thorlabs/test_abstract.py

Fix flakey thorlabs test

---

src/instruments/yokogawa/yokogawa6370.py
tests/test_yokogawa/test_yokogawa_6370.py

I'm reworking the Yokogawa 6370, as I want to use more methods.
It's not ready yet. I'm adding tests as well and going to test it on my device.

Yokogawa 6370 expansion
