.pylintrc, instruments/doc/examples/ex_thorlabstc200.py, instruments/doc/source/apiref/thorlabs.rst, instruments/instruments/abstract_instruments/comm/loopback_communicator.py, instruments/instruments/abstract_instruments/comm/serial_communicator.py, instruments/instruments/abstract_instruments/instrument.py, instruments/instruments/errors.py, instruments/instruments/tests/test_property_factories.py, instruments/instruments/tests/test_thorlabs/__init__.py, instruments/instruments/tests/test_util_fns.py, instruments/instruments/thorlabs/__init__.py, instruments/instruments/thorlabs/_abstract.py, instruments/instruments/thorlabs/_cmds.py, instruments/instruments/thorlabs/_packets.py, instruments/instruments/thorlabs/_utils.py, instruments/instruments/thorlabs/lcc25.py, instruments/instruments/thorlabs/pm100usb.py, instruments/instruments/thorlabs/sc10.py, instruments/instruments/thorlabs/tc200.py, instruments/instruments/thorlabs/thorlabs_utils.py, instruments/instruments/thorlabs/thorlabsapt.py, instruments/instruments/util_fns.py, instruments/requirements.txt
- Adds support for instruments to respond with an "acknowledgement" string via `_ack_expected` function
- Adds support for instruments to send a "prompt" string (eg `">"`) after finishing with a previous command
- Add Thorlabs TC200
- Refactor Thorlabs SC10 and LCC25
- Adds a little bit of value checking for enum, unitful, and bool property factories
- Includes a few bug fixes
Regarding ack and prompt strings, here is the assumed format:
Sending a command: `CMD=1` returns `[ack][term][prompt][term]`
Sending a query: `CMD?` returns `[ack][term]response term[prompt][term]`
=> Refactor of PR #56

instruments/instruments/abstract_instruments/function_generator.py, instruments/instruments/abstract_instruments/multimeter.py, instruments/instruments/agilent/__init__.py, instruments/instruments/agilent/agilent33220a.py, instruments/instruments/agilent/agilent34410a.py, instruments/instruments/generic_scpi/scpi_function_generator.py, instruments/instruments/tests/test_agilent/__init__.py
Agilent classes linted, and the corresponding abstract base classes have been changed. These changes to the ABCs technically break Python <= 3.2 's ability to block instantiating a class that has not defined all its abstract methods. This is because in Python 3.3 the `@property` decorator was updated such that it can directly wrap an `@abc.abstractmethod` decorator. According to the docs (https://docs.python.org/3/library/abc.html) the `abc.abstractproperty` method is deprecated.
As we move forward with more test coverage and toward supporting Python 3, I'd rather we do things the most up to date way possible. In this case, if tests pass under Python 2 and 3, then there isn't any issues about abstract methods that haven't been defined for Python <= 3.2
=> pass pylint on agilent classes

.travis.yml, instruments/dev-requirements.txt, instruments/instruments/tests/test_property_factories.py, instruments/instruments/util_fns.py
Adds `bounded_unitful_property` to `util_fns.py`. This builds on `unitful_property` by easily allowing for devs to assign dynamic bounds to unitful properties. By default it will query the instrument for min and max values, but this can be overridden to use static boundary values. These can also be done directly though `unitful_property` now, but `bounded_unitful_property` is a much cleaner way which also returns properties for direct access to the min and max values.
=> Bounded unitful property

instruments/instruments/abstract_instruments/signal_generator/channel.py, instruments/instruments/holzworth/__init__.py, instruments/instruments/holzworth/holzworth_hs9000.py, instruments/instruments/other/__init__.py, instruments/instruments/tests/test_holzworth/test_holzworth_hs9000.py, instruments/instruments/tests/test_property_factories.py, instruments/instruments/util_fns.py
Holzworth changes:
- Refactors the Holzworth HS9000 a little bit to make sure everything is in line
- Passes all linting on holzworth files
- Adds full coverage for current functionality
Other changes:
- Changes `unitful_property` to use `split_unit_str` on the getter function to handle returns from instruments that also include a unit in the response.
=> Holzworth work

instruments/.pylintrc, instruments/doc/source/apiref/keithley.rst, instruments/instruments/abstract_instruments/electrometer.py, instruments/instruments/hp/__init__.py, instruments/instruments/keithley/__init__.py, instruments/instruments/keithley/keithley195.py, instruments/instruments/keithley/keithley2182.py, instruments/instruments/keithley/keithley580.py, instruments/instruments/keithley/keithley6220.py, instruments/instruments/keithley/keithley6514.py, instruments/instruments/tests/test_keithley/test_keithley2182.py, instruments/instruments/tests/test_keithley/test_keithley6220.py, instruments/instruments/tests/test_keithley/test_keithley6514.py, instruments/instruments/tests/test_property_factories.py, instruments/instruments/util_fns.py
Includes the following:
- lints keithley instrument files
- adds unit tests for 2182, 6220, 6514
- improves `bounded_unitful_property` to use `assume_units` for the boundary checker
No tests for the 195 and 580. Those are a pain in the bum and are going to take some time to write tests for. I'd rather get this in and move on for now.
=> Lint keithley

instruments/instruments/__init__.py, instruments/instruments/abstract_instruments/comm/file_communicator.py, instruments/instruments/config.py, instruments/instruments/errors.py, instruments/instruments/thorlabs/thorlabsapt.py, instruments/instruments/units.py, instruments/instruments/util_fns.py
Lints those extra files, like `util_fns.py`, `units.py`, `config.py`, etc.
While I was at it, I found some code for py26 logging in `util_fns.py` that I've removed. Py27 is the oldest I want to be supporting so I went ahead and removed it and any references.
=> Lint accessory files

instruments/abstract_instruments/comm/file_communicator.py, instruments/abstract_instruments/comm/gi_gpib_communicator.py, instruments/abstract_instruments/comm/loopback_communicator.py, instruments/abstract_instruments/comm/serial_communicator.py, instruments/abstract_instruments/comm/socket_communicator.py, instruments/tests/test_comm/test_file.py, instruments/tests/test_comm/test_gi_gpibusb.py, instruments/tests/test_comm/test_loopback.py, instruments/tests/test_comm/test_serial.py, instruments/tests/test_comm/test_socket.py, instruments/tests/test_comm/test_usbtmc.py
Adds a bunch of tests for the communication layers
Even includes a bugfix or two for the file comm layer under Py3+
=> Comm tests

instruments/abstract_instruments/comm/gi_gpib_communicator.py, instruments/abstract_instruments/instrument.py, instruments/tests/test_base_instrument.py, instruments/tests/test_comm/test_gi_gpibusb.py
This should fix issue #104 and make `binblockread` a little more self consistent. I don't believe there was an error in that function, but this will at least make sure that its internals is dealing with `bytes` instead of `str`.
=> Bugfixes for #104

instruments/tektronix/tektds224.py
Increases the connect timeout for the TekTDS224 to give enough time to transfer waveforms.
=> Increase connection timeout for tektds224 for larger transfers

instruments/__init__.py, instruments/abstract_instruments/instrument.py, instruments/tests/test_base_instrument.py
This adds a reading loop to the `binblockread` function. Over the weekend I discovered that if a transfer takes longer than the specified connection timeout, then the rest of the data just gets stuck in the buffer and passed onto the next query.
The solution here is to keep reading if we haven't read in the specified number of bytes yet. If we are short bytes, and a read does not result in any more bytes, I added a few more retries just in case the instrument is still processing. After two additional retries, there must have been an error and so an `IOError` is raised.
=> Binblockread retries

instruments/__init__.py, instruments/abstract_instruments/comm/serial_communicator.py, instruments/abstract_instruments/comm/socket_communicator.py, instruments/abstract_instruments/comm/visa_communicator.py, instruments/tests/test_comm/test_serial.py, instruments/tests/test_comm/test_socket.py
Fixes an inf loop problem that would happen when you specify to read until a termination character is found, but your connection times out. This would cause the read to be re-called, which would in turn timeout, etc.
Problem found by @CatherineH
=> Fix read timeout

instruments/__init__.py, instruments/abstract_instruments/instrument.py, instruments/tests/test_base_instrument.py, instruments/tests/test_toptica/test_toptica_topmode.py, instruments/toptica/topmode.py
Looks like the Toptica Topmode laser will send more than one ACK message for some commands. This PR adds support for `_ack_expected` returning a list of messages that must be read in.
=> Add support for multiple ACKs

instruments/abstract_instruments/comm/usbtmc_communicator.py, instruments/tests/test_comm/test_usbtmc.py
This adds an implementation for the `USBTMCCommunicator` class, fixing issue #120
=> Fix USBTMC timeout property

instruments/abstract_instruments/comm/usbtmc_communicator.py, instruments/tests/test_comm/test_usbtmc.py
Fixes a problem with `USBTMCCommunicator` where termination characters were being appended once in the class, and then again in the downstream `usbtmc` package. In addition, it also fixes setting the termination character in the `usbtmc` package by sending an `int` instead of a `str`.
Address issue #121
=> Fix USBTMC terminator char problems

instruments/abstract_instruments/comm/usbtmc_communicator.py, instruments/tests/test_comm/test_usbtmc.py
Changes the `USBTMCCommunicator.flush_input()` implementation to `pass` instead of raising an exception. Flushing doesn't make much sense for these types of connected instruments, but some code does call this function. So for now this will just pass unless this causes other magical instrument problems.
Addresses issue #122
=> Fix USBTMC flush_input, and add a missing docstring

instruments/abstract_instruments/comm/usbtmc_communicator.py, instruments/tests/test_comm/test_usbtmc.py
This PR pulls in the changes made to fix the following issues: #120 #121 #122 #127
Work was mainly done in PRs #124 #125 #126
After this, `v0.1.1` can be made ready.
=> Fixes for USBTMCCommunicator

doc/examples/ex_topticatopmode.py, doc/examples/toptica/91-toptica.rules, doc/examples/toptica/ex_topticatopmode.py, instruments/tests/test_toptica/test_toptica_topmode.py, instruments/tests/test_toptica/test_toptica_utils.py, instruments/toptica/topmode.py, instruments/toptica/toptica_utils.py
Copy of PR #119 just with develop as the base branch
This PR contains several updates relating to toptica topmode charm controller.
this includes:
fixing a command spelling error
adding the udev rule
adding firmware and topmode charm controller serial number
handling the situation when no laser is plugged into the controller
=> Ch toptica functionality

doc/source/apiref/ondax.rst, instruments/ondax/__init__.py, instruments/ondax/lm.py, instruments/tests/test_ondax/test_lm.py
The Ondax Surelock Laser module has a communication protocol with few patterns, thus there is little to be gained other than confusion in using factory modules.
=> added surelock laser module

doc/examples/qubitekk/ex_qubitekk_mc1.py, doc/source/apiref/qubitekk.rst, instruments/qubitekk/__init__.py, instruments/qubitekk/mc1.py, instruments/tests/test_qubitekk/test_qubitekk_mc1.py
This PR adds support for the qubitekk MC1 motor controller.
=> adding mc1

instruments/abstract_instruments/comm/visa_communicator.py
- Temporarily resolves an issue regarding version checking for `pyvisa`
This should be redone in a more robust way to prevent this from continuously having problems. Or at this point, just drop `pyvisa < 1.6`.
=> Fix pyVISA version checking

dev-requirements.txt
Version `1.7.0` of `pylint` introduces a bunch of new rule checks which break the current build. While we work on making the changes, the build should remain green on the previous version.
This PR fixes the version to `1.6.5`, which is really something I should have done a long time ago.
=> Freeze pylint to version 1.6.5

requirements.txt
Looks like they're actively working on a new 0.15 version of `ruamel.yaml`, which doesn't seem to currently compile on Python 3.4 Travis environments, so for now I'm just going to stick with the 0.14 version.
=> Pin ruamel version

instruments/agilent/agilent33220a.py, instruments/generic_scpi/scpi_function_generator.py, instruments/generic_scpi/scpi_multimeter.py, instruments/lakeshore/lakeshore475.py, instruments/picowatt/picowattavs47.py, instruments/qubitekk/mc1.py, instruments/srs/srs345.py, instruments/tests/test_property_factories/test_bool_property.py, instruments/tests/test_property_factories/test_bounded_unitful_property.py, instruments/tests/test_property_factories/test_enum_property.py, instruments/tests/test_property_factories/test_int_property.py, instruments/tests/test_property_factories/test_string_property.py, instruments/tests/test_property_factories/test_unitful_property.py, instruments/tests/test_property_factories/test_unitless_property.py, instruments/thorlabs/lcc25.py, instruments/thorlabs/sc10.py, instruments/util_fns.py
This PR adds optional `set_cmd=None` parameter to each property factory to allow for those rare instruments that have asymmetric command strings for getting vs setting. We have one of those in the repo right now, so this will let us refactor that instrument to use the property factories.
This also renames the main parameter of those functions from `name` to `command` to go in line with `set_cmd`.
If `set_cmd` is not specified, then `command` is used for both the getting and setting string.
(address issue #148 )
=> Issue 148 - Property templates should support different commands for getting vs setting

instruments/abstract_instruments/comm/usbtmc_communicator.py, instruments/tests/test_comm/test_usbtmc.py
The `python-usbtmc` package seems to expect an `int` value for the terminator character, and an `int` representing the number of seconds for the timeout.
For timeout, we were actually providing a value in milliseconds. It looks like library actually expects it in seconds, and then it internally converts this value to milliseconds.
This PR should fix these issues.
=> Fix timeout and terminator for USBTMC

instruments/abstract_instruments/comm/visa_communicator.py
The write_raw method should probably call the write_raw method in pyvisa
=> Change write to write_raw when communicating using visa

README.rst, requirements.txt
A new version of `python-quantities` has finally been published to address the issue with `numpy>=1.13.0`. This PR ensures that we're using the newest version so that users can use newer versions of numpy if they so choose.
I'm also sneaking in a small fix for the badges in the readme with this patch so that they actually point to the master branch of IK on Coveralls.
=> Use new version of quantities

instruments/__init__.py
- Removes version pin for `numpy`
- Adds version requirement of `quantities>=0.12.1` to ensure users don't have issues with `numpy>=1.13.0`
=> Bump version 0.4.0 -> 0.4.1

instruments/abstract_instruments/comm/socket_communicator.py, instruments/tests/test_comm/test_socket.py
Addresses issue #189 by correctly passing `socket.SHUT_RDWR` into the socket shutdown method.
=> Fix socket.shutdown function call (issue #189)

.travis.yml, README.rst, requirements.txt, setup.py, tox.ini
Changes
------------
- Adds Python 3.7 to the list of supported versions. Soon after this Py34 will be removed due to EOL.
- This also (hopefully) fixes the PyPI project description rendering
- Changes Travis to only publish to PyPI if it is the latest version of Python running the final build on the tagged release
=> Python 3.7 support

.travis.yml, README.rst, setup.py, tox.ini
Address issue #198 
This will remove Python 3.4 as a supported version for v0.5
=> Drop support for Python 3.4

instruments/hp/hp6632b.py
Fixes `DeprecationWarning` from Py37 where checking if value is in enum will raise `ValueError` in Py38
=> Fix checking if value is in IntEnum (issue #197)

instruments/generic_scpi/scpi_function_generator.py, instruments/tests/test_generic_scpi/test_scpi_function_generator.py
Changes
----------
- Fix a bug with `SCPIFunctionGenerator.function`, where the associated enum was undefined.
- Add unit tests for this class
=> Fix bug with SCPIFunctionGenerator.function, add tests

instruments/agilent/agilent33220a.py, instruments/tests/test_agilent/test_agilent_33220a.py
Changes
----------
- Fix bugs in Agilent 33220a
- Add unit tests for Agilent 33220a
=> Fix Agilent 33220a, add tests

dev-requirements.txt, instruments/abstract_instruments/function_generator.py, instruments/tests/__init__.py, instruments/tests/test_abstract_inst/test_function_generator.py, instruments/tests/test_generic_scpi/test_scpi_function_generator.py
Changes
------------
- These changes align the `FunctionGenerator` abstract instrument to have an API consistent between single- and multi-channel function generator instruments. See issue #156 for API related details.
- Changes the tests for the `SCPIFunctionGenerator` to simultaneously test both API access methods (eg, using `inst.frequency` and `inst.channel[0].frequency` do the same thing)
=> Function Generator single/multi-channel consistency

.travis.yml, README.rst, dev-requirements.txt, doc/examples/minghe/ex_minghe_mhs5200.py, doc/source/apiref/minghe.rst, instruments/__init__.py, instruments/abstract_instruments/comm/loopback_communicator.py, instruments/abstract_instruments/comm/serial_communicator.py, instruments/abstract_instruments/function_generator.py, instruments/agilent/agilent33220a.py, instruments/generic_scpi/scpi_function_generator.py, instruments/hp/hp6632b.py, instruments/minghe/__init__.py, instruments/minghe/mhs5200a.py, instruments/tests/__init__.py, instruments/tests/test_abstract_inst/test_function_generator.py, instruments/tests/test_agilent/test_agilent_33220a.py, instruments/tests/test_comm/test_loopback.py, instruments/tests/test_generic_scpi/test_scpi_function_generator.py, instruments/tests/test_minghe/test_minghe_mhs5200a.py, instruments/tests/test_thorlabs/test_thorlabs_apt.py, instruments/thorlabs/_abstract.py, instruments/thorlabs/_packets.py, instruments/thorlabs/thorlabsapt.py, setup.py, tox.ini
Bringing in the following PRs to master for version `v0.5.0`
- #200 drop support for Python 3.4
- #201 fix issue #197 HP6632b.check_error_queue raises warning in Py37
- #167 Improvements to the Thorlabs APT drivers
- #202 Fix bug in `SCPIFunctionGenerator.function`
- #203 Fix bug in `Agilent33220a`
- #206 Create a consistency for the API for function generators to provide consistency across single- and multi-channel instruments
- #150 Add support for Minghe MHS5200
- #207 Docstring modifications for the MHS5200
=> Develop -> master for v0.5.0

instruments/glassman/glassmanfr.py
These changes were grabbed from francois/master that weren't included in my last PR.
=> A few fixes from Francois for the glassman FR

instruments/thorlabs/tc200.py
```
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-14-4720703b9261>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
int(response) % 2 is 1.0
```
> The == operator compares the values of both the operands and checks for value equality. Whereas is operator checks whether both the operands refer to the same object or not.
> - https://www.geeksforgeeks.org/difference-operator-python/
=> Fix: SyntaxWarning: "is" with a literal. Did you mean "=="?

.travis.yml, README.rst, setup.py, tox.ini
First step to fulfilling #199 
This PR drops support for Py2.7 which is now EOL
Also drops support of Py3.5, which while not EOL, is not supported by other projects such as `scipy`. Mostly though, I want to use f-strings.
=> Officially drop Py2.7 and Py3.5

doc/source/intro.rst, requirements.txt, setup.py
Without Py2 being supported anymore, the `enum34` is no longer needed. And its apparently keeping pyinstaller from working #199
=> Remove enum34 from dependencies

doc/source/apiref/newport.rst, instruments/newport/__init__.py, instruments/newport/agilis.py, instruments/tests/test_newport/test_agilis.py
Added a new instrument for Newport Agilis devices. Currently, only the
AG-UC2 Controller is supported. Added the controller to the respective
ini file in the newport folder.
Axis class implemented to send device specific commands. This can be
used from other controllers, once implemented, as well.
Some caveats / non-implemented and only partially tested routines are
noted on top of the `agilis.py` file. I don't have a device with a limit
switch available for testing, therefore, some routines that only work
on such devices are not implemented and some routines are untested. The
doc strings for every routine states this clearly as well.
A full test suite for all functions is also provided.
Everything tested with tox for py36, py37, and py38. All tests succeeded.
=> Added instrument: Newport Agilis

instruments/srs/srsdg645.py, instruments/tests/test_srs/test_srsdg645.py
Here now the promised enhancements for the SRS645 delay generator.
Added routines for enabling burst mode and controlling all sub
properties. Set/get implemented for all sub menus of burst mode.
A full test suite for each of the new functions has been implemented
as well.
Every call has been tested with an actual instrument and is functional.
Local test results:
tox testing: all passed
pylint rating: 10/10
=> Enhancement: SRS645 delay generator added burst mode support

doc/examples/ex_maui.ipynb, doc/source/apiref/index.rst, doc/source/apiref/teledyne.rst, instruments/__init__.py, instruments/teledyne/__init__.py, instruments/teledyne/maui.py, instruments/tests/test_teledyne/test_maui.py, requirements.txt
Changes:
- maui.py and associated folder structure created
- Communication via pyvisa-py: requirements.txt extended
- Requires LXI support of oscilloscope
- test suite with full coverage of all new functions
- Inherits from `Oscilloscope`
- read_waveform has additional argument to allow grabbing math traces
in a useful way (see docstring)
- Implemented features are:
- Trigger control: Trigger sources enum class is automatically
regenerated when user changes number of channel on their specific
oscilloscope
- Channel control
- Math function
- Measurement control
- Data Sources subclass
- Extensive doc strings with notes and warnings
- Not all scopes will have all functions available
- User needs to insure that functions are available on their MAUI
oscilloscope
- Updated documentation
- …
=> Support of Teledyne-LeCroy MAUI enabled oscilloscopes

instruments/srs/srsdg645.py, instruments/tests/test_srs/test_srsdg645.py
Trying to put some code where my mouth is :wink: (#246): With the hardware present I went through the `srsdg645.py` file and extended the test suite to increase the coverage. Every routine now has a test. The only uncovered line is 96-97:
```python
if isinstance(filelike, GPIBCommunicator):
filelike.strip = 2
``` 
While going through the class I noticed a few inconsistencies. Several routines ha no `assume_units()` call included, while some others did. I extended all of those routines (and the respective tests) to contain an `assume_units` call, defaulting to SI units when none were given. Details on which routines in commit message below.
One test was renamed and restructured, since it didn't test at all what it was named after... Now it does, and is formatted like every other test.
=> Enhancements to SRS DG645 test suite and class

instruments/lakeshore/lakeshore475.py, instruments/tests/test_lakeshore/test_lakeshore340.py, instruments/tests/test_lakeshore/test_lakeshore370.py, instruments/tests/test_lakeshore/test_lakeshore475.py
Full test suite for all three existing Lakeshore instruments written.
While writing test suite, fixed 4 bugs in `lakeshore475.py`:
- Two send strings were stiched together as a string and an integer,
not allowed anymore. Switched to proper string formatting using an
f-string.
- Two TypeError messages contained the wrong text (likely a copy, paste
error). This is now fixed.
=> Test Suite for all Lakeshore instruments, Bug Fix Lakeshore475

instruments/rigol/rigolds1000.py, instruments/tests/test_rigol/test_rigolds1000.py
**Test suite**
Created tests for Rigol DS1000.
**Bug fixes for `rigolds1000.py`**
- For the channel couplings of this oscilloscope, the test was implemented according to the manual, however failed. I believe that this was due to an error in the `RigolDS1000Series` class, `rigolds1000.py` file line 110. My proposed fix is attached to the commit [1d54486](https://github.com/Galvant/InstrumentKit/commit/1d544862935a3af934d65a262aaaefabde7500e8) in this PR: I moved the `Couplings` enum from the main class into the `Channel` inner class. This makes sense, since only channels have these couplings, and is analogue to other oscilloscopes, e.g., Tektronix DPO70000.
- In `bool_properties` calls, named arguments were not appropriately
named for `inst_true` and `inst_false`. Corrected.
- All bug …
=> Tests rigolds1000

instruments/tests/test_yokogawa/test_yokogawa7651.py, instruments/tests/test_yokogawa/test_yokogawa_6370.py, instruments/yokogawa/yokogawa6370.py
**Tests**
- Full test suite for Yokogawa 7651
- Extended test suite for Yokogawa 6370 for complete coverage
**Bug fixes**
- Found two small bugs in Yokogawa 6370:
- Methods `data` and `wavelength`, both return the data for the
active trace, returned the method itself instead of the data.
- These were also the two untested routines.
=> Tests for Yokogawa 7651 and tests + BF for Yokogawa 6370

instruments/tektronix/tekawg2000.py, instruments/tests/test_tektronix/test_tekawg2000.py
Full test suite created - this time using hypothesis quite intensively. @scasagrande: I guess this is would be preferred over the other tests, let me know what you think. Happy to adjust / change / ...
Bug fixes for `TekAWG2000` class:
- Enum names were called instead of value (twice) in properties getter
for `polarity` and `shape. Now switched to value.
- `upload_waveform`:
Rearranged error checking: Now, no instrument changes are sent when a
`ValueError` is encountered. This is not necessarily a bug, but I
think it is better this this way.
- Fixed the following depreciation warning:
"DeprecationWarning: tostring() is deprecated. Use tobytes() instead."
=> Test suite and BF for Tektronix AWG2000

instruments/tektronix/tekdpo4104.py, instruments/tests/test_tektronix/test_tekdpo4104.py
**Full coverage test suite for Tektronix DPO4104**
Trying to make use of hypothesis where it makes sense and leave it away where it
doesn't.
**Bug fixes for `tekdpo4104.py`:**
- Instead of the new value to set, the documentation was passed on
in the `_parent_property` routine. This routine is only used once,
however, a usage scenario is written but has likely never been
tested before. The test that does what this property is supposed to
do passes now with the fix.
- Reading ASCII data from a data source used `map` and then directly
transferred to an `ndarray`. This was fine in python 2, not anymore
though. Fixed on line 114.
- Reading binary data is tested now. The test however failed since the
next command issued left only a termination character. The binary data
is read using …
=> Test suite for Tektronix DPO4104 and bug fixes

instruments/srs/srsctc100.py, instruments/tests/test_srs/test_srsctc100.py
Full coverage test suite for SRS CTC-100
Minor bug fix for `srsctc100.py`:
`get_log_point` method in `Channel` subclass assigned a quantity to
return values without converting them to numbers. Returned were thus
unitful strings. While technically not a bug, this behavior does not
fit together with the rest of this class or the general returns in ik
Now floats are returned.
=> Test suite and BF for SRS CTC-100

instruments/tektronix/tekdpo70000.py, instruments/tests/test_tektronix/test_tekdpo70000.py
This PR needs some discussion, there are certain things in here that are not ideal - it went a bit out of hand... First the changes:
**Bug Fixes**:
- Two properties were called as `unitful_property` instead of
`enum_property`. As the "unit", an enum was given. Seems to be a
copy&paste error.
- The second of these properties also had the wrong enum specified.
Swapped out for correct enum.
- Double checked all fixes with manual.
**Test suite**:
- Full, and likely overkill, test suite added (needs discussion).
- One test that is intentionally skipped added for binary waveform
reading (needs discussion).
- Full coverage not achieved.
**Discussion points**:
1. I'm using quite some `@pytest.mark.parametrize` to parametrize every channel and every math call. I don't think this is actually …
=> Test suite and BFs for TekDPO70000

instruments/tests/test_util_fns.py
Test for property factories were extended to test the following:
- Setter and getter work according to the expected format.
- Assert that the property getter calls its host classes `query` method
- Assert that the property setter calls its host classes `sendcmd`
method
A test class is set up using a fixture. `query` and `sendcmd` are implemented in a simple way such that we can assert easily that they are called using mocker spies. After getting / setting values, the spies are used to assert that the call has taken place, as discussed in issue #258.
=> Tests that proprety factories invoke host classes `query` and `sendcmd` methods

instruments/tests/test_thorlabs/test_thorlabs_pm100usb.py, instruments/thorlabs/pm100usb.py
Test suite with full coverage added
**Bug fixes** (details in code remarks below): 
- Could not find a programmers manual on this instrument.
- Replaced a `sendcmd` with a query, since a value is expected from the
instrument. No read provided, thus this is likely a bug.
- When creating `self._flags` while initializing a sensor, an integer
was compared to a string. String now first converted to integer for
comparison.
I couldn't find a programming manual for this instrument - I'll keep looking, but the bug fixes are my best guess on how it should work. It seems clear that the way it is right now, it cannot produce the expected outcome.
=> Test suite and BFs for Thorlabs PM100USB

instruments/tektronix/tektds5xx.py, instruments/tests/test_tektronix/test_tktds5xx.py
Test suite with full coverage
- Tests for `get_hardcopy` routine is a bit creative, but couldn't
find any manual entry for what is done there.
**Bug fixes**:
- Typos
- map(float, list_of_string) not allowed anymore, switched to directly
transferring to `np.array` with specific `dtype`.
- `flush_input` in `read_waveform` replaced with reading one character.
Manual states that newline character is present after binary block.
- Enums called with name instead of value -> fixed, now called properly
- `get_hardcopy` routine tried to unpack read data. However, the
`read` routine already decodes it using "utf-8" as the default
encoding already. Thus: need to encode again before using
`struct.unpack` to unpack them.
- Class had `import time` and `from time import sleep` and used `sleep`
and …
=> Test suite and BFs for Tektronix TDS5xx

instruments/keithley/keithley195.py, instruments/tests/test_keithley/test_keithley195.py
Full coverage test suite
BFs:
- Transfer queried values to bytes before using `struct.unpack`.
- Do subsequent comparisons on bytes as well.
- Remove `if self._testing` statement to skip a sleep time. In the test,
mock `time.sleep` for speedup and ensure it was called with
a 2 seconds argument.
=> Tests and BFs for Keithley 195

instruments/agilent/agilent34410a.py, instruments/tests/test_agilent/test_agilent_34410a.py
Test suite extended for full coverage.
Minor bug fix: Returning `int('9.91000000E+37')` in `read_last_data`
returns a `ValueError`, and is not consistent with the routine otherwise
returning a `float`. Changed to returning a float.
=> Test suite update and BF for Agilent 34410a

instruments/keithley/keithley580.py, instruments/tests/test_keithley/test_keithley580.py
Test suite with full coverage added
**BFs**:
- Removed inaccessible code block
- Replaced a not in `enum` statement with a check of `isinstance`, now
the test is compatible to the error description that is raised.
- Getting the 'auto' input was previously not possible, fixed the
respective property getter.
- Fixed typos
- Fixed status word getting such that an IOError can actually be
raised now if failing to receive a status word after given number of
tries
- Fixed reading of bytes: same issue as in Keithley195, trying to
unpack a string with `struct.unpack`. Now consistent and functional.
=> Test suite and BFs for Keithley580

instruments/tektronix/tektds224.py, instruments/tests/test_tektronix/test_tektronix_tds224.py
Test suite extended for full coverage
**Bug fixes**:
- Using `map` to convert a list from string to floats is Py2 legacy and
not allowed anymore. Now using `numpy` conversions.
- Remove `if not self._testing` statement to introduce `time.sleep`:
instead mocking time.sleep in test suite now with an autouse fixture.
(I had a some work stashed away...)
=> Test suite and BFs for Tektronix TDS224

doc/source/apiref/gentec-eo.rst, doc/source/apiref/index.rst, instruments/__init__.py, instruments/gentec_eo/__init__.py, instruments/gentec_eo/blu.py, instruments/tests/test_gentec_eo/test_blu.py
To mix it up... here's a new instrument instead of a test
Added support for gentec-eo's Blu series power meters. These power
meters connect via bluetooth, the bluetooth dongle showsvup as a regular
serial port. In addition, they can be plugged into a USB port and vshow up
as a regular serial interface as well.
Full test suite added as well.
All routines have example doc strings with detailed examples.
Added to docs.
=> Gentec-eo Blu support and test suite

instruments/newport/agilis.py, instruments/tests/test_newport/test_agilis.py
I think one of the first full drivers I submitted... it had some issues. Not fully tested and some `@property` had different types in getters and setters... my apologies.
Here, I fixed those issues and extended the test suite. Also did a little bit of docstring cleanup for changed routines.
Oh: and the sleep is now mocked out for the tests, which speeds things up :smiley: 
**Test suite:**
- Extended to fully cover `agilis.py`
- Time is now mocked out for all tests to speed things up
**Enhancements / Fixes:**
- `@property` did not always return the same type. Corrected for
multiple routines and tested with hardware.
- Also adjusted doc strings to represent these changes.
- Change `from time import sleep` to `import time` for mocking
=> Improved testing and enhancements of Newport Agilis support

instruments/fluke/fluke3000.py, instruments/tests/test_fluke/test_fluke3000.py
Full coverage test suite.
Changes & BF for `fluke3000.py`:
- Instead of returning an `AttributeError` it is now raised (as for
other methods already too).
- Fixed a typo
=> Tests and BF for Fluke3000

instruments/tests/test_keithley/test_keithley580.py
The test now passes. Set the relative deviation allowed to 1e-6. 
The funky thing is: according to the pytest documentation [here](https://docs.pytest.org/en/5.4.1/reference.html#pytest-approx), this should have been the default setting already. 
My local `tox` with all fresh environments passes now. Let's see what Travis says...
See discussion in PR #270
=> BF: Adjust `pytest.approx` statement such that Keithley580 tests pass

dev-requirements.txt
Hopefully this fixes the pytest version mismatch we are seeing in our travis runs, which is causing 1 of our unit tests to fail due to, what appears to be, a bug in pytest 5.2.1
@trappitsch
=> Update pytest to version 6.1.1

instruments/newport/errors.py, instruments/tests/test_newport/test_errors.py
Simple test suite with full coverage. Time stamps are only tested for existence. Further tests are probably not required.
If further tests for timestamps are wanted we might consider to add `pytest-freezegun` to the `dev-requirements.txt` in order to freeze timestamps. (Maybe should include that just for the awesome name :wink:).
**Bug fix:**
The timedelta creation for the timestamp made not much sense to me and resulted in an error, even when just executing it by itself. Creating a timestamp that is as close to the one given if no specific `datetime` is provided.
=> Test suite and BF for Newport's `error.py`

instruments/abstract_instruments/comm/visa_communicator.py, instruments/abstract_instruments/instrument.py, instruments/tests/test_base_instrument.py
Switch `import visa` and dependent statements to `import pyvisa`.
Takes care of depreciation warning to avoid further conflicts with other
package. See issue #273 
@scasagrande Was indeed fairly minimal
=> Rename visa to pyvisa

instruments/tests/test_thorlabs/test_abstract.py, instruments/tests/test_thorlabs/test_packets.py, instruments/thorlabs/_abstract.py, instruments/thorlabs/_packets.py
Test suites for both thorlabs helper classes with full coverage. Mainly (only?) used by ThorlabsAPT.
Bug fixes for `_abstract.py`:
- Re-stated `if timeout` to `if timeout is not None` to avoid
ambivalence if a timeout of zero is specified (as done in the test to
speed things up). By default, `timeout` is set to `None`.
Bug fixes for `_packets.py`:
- Removed inaccessible code.
- `__str__` had several errors in it and couldn't print when given
variables were `None` (which some of them always have to be)
- `parameters` setter previously set `message_id` instead of parameters.
=> Tests and BFs for Thorlabs `_abstract` and `_packets` helper classes

instruments/newport/newportesp301.py, instruments/tests/test_newport/test_newportesp301.py
This one is a monster, but it's finally done. Found some bugs / typos on the way too, see separate comments.
Bug fixes:
- Typos
- Import changes for mocking in tests
- Setter shouldn't be called with a default argument for argument
- Change `u.Quantity` call to `u.Unit` call
- Remove error call that doesn't seem to make sense
- Check for `max_wait is not None` in `wait_for_motion`
- Add keywords to docstring in `setup_axis`
- Correct copy / paste error in error message in `setup_axis`
Test suite uses a lot of mocking in order to not go through the crazy calls that permanently happen to the routine. This should be okay since the mocked out routines are thoroughly tested separately.
=> BF and full coverage test suite for NewportESP301

instruments/hp/hp3456a.py, instruments/hp/hpe3631a.py, instruments/tests/test_hp/test_hp3456a.py, instruments/tests/test_hp/test_hp6624a.py, instruments/tests/test_hp/test_hp6632b.py, instruments/tests/test_hp/test_hp6652a.py, instruments/tests/test_hp/test_hpe3631a.py
Full cov test suites for:
- HP3456a
- HP6624a
- HP6632b
- HP6652a
- HPe3631a
Bug fix:
- HPe3631a: Raise an error that was previously returned
Changes:
- HP3456a: Remove `if self._testing` statement to not do `time.sleep`
during tests. Instead use an automatically used pytest fixture to
mock out `time.sleep`.
=> Tests and some BFs for HP devices

instruments/keithley/keithley485.py, instruments/tests/test_keithley/test_keithley485.py
Test suite now includes full coverage.
Bug fixes:
- Quantities error corrected
- If statement for error raising corrected, previous comparison was
impossible to achieve
- Error catching in `_parse_measurement`. Errors were previously raised
in a `try`, `except` statement, however, the wrong error messages
would be displayed if these errors in fact got raised
=> Test suite and BF for Keithley 485

instruments/qubitekk/cc1.py, instruments/tests/test_qubitekk/test_qubitekk_cc1.py
Full coverage test suite
BF:
- The `try` statement in the property getter for `count` did not work
as expected and was exempted from coverage. Removed the exemption and
corrected the statement. There was a `FIXME` comment attached to it,
should be fixed now.
=> Tests and BF for Qubitek CC1

.travis.yml, tox.ini
This PR changes how we do testing in CI, and by extension, what we consider a passing build.
The core of this is to use `tox` as the venv manager in order to create known environments for the tests to execute against. In addition, it allows developers to run tests in the same fashion as they would be run in CI.
While we are [not using a `src` folder](https://blog.ionelmc.ro/2014/05/25/python-packaging/) (although funny enough, IK did have one several years ago), moving to `tox` as the center focus for creating and deploying our test environments will help fix a number of issues. 
#288
=> Use tox in travis

instruments/srs/srs830.py, instruments/tests/test_srs/test_srs830.py, instruments/tests/test_srs/test_srsdg645.py
- Full coverage test suite for SRS instruments
- Removed `# pragma: no cover` statements and tested these lines
- Removed `if not self._testing` to invoke a `time.sleep`, which is now
simply mocked out in the test using an automatically used fixture.
- Fixed typos
If I didn't miss anything, this should be the last push for fully testing all specific instruments and finish the list in #246.
=> Tests for SRS DG645 and 830

setup.cfg
With the release of pyserial 3.5 the build is currently broken as our tests don't pass with it #298 . This PR disables support for it until we can fix the root problem.
=> Remove support for new pyserial 3.5 until we fix it

instruments/generic_scpi/scpi_instrument.py, instruments/tests/test_generic_scpi/test_scpi_function_generator.py, instruments/tests/test_generic_scpi/test_scpi_instrument.py, instruments/tests/test_generic_scpi/test_scpi_multimeter.py
- All three instruments now with full coverage
- Added tests to SCPI Function Generator
- Added tests to SCPI Multimeter
- Created tests for SCPI Instrument
- Corrected a typo / copy paste error: Contrast error message returned
description for brightness instead of contrast.
=> Tests and typo fix for Generic SCPI Instruments

instruments/tests/test_base_instrument.py, setup.cfg
Adjusted the mocker that faked serial ports for appropriate initialization, see code comment below.
This should take care of #298
=> Fix issue with pyserial3.5 and remove pinned requirement pyserial<3.5

instruments/abstract_instruments/optical_spectrum_analyzer.py, instruments/abstract_instruments/oscilloscope.py, instruments/tests/test_abstract_inst/test_electrometer.py, instruments/tests/test_abstract_inst/test_function_generator.py, instruments/tests/test_abstract_inst/test_multimeter.py, instruments/tests/test_abstract_inst/test_optical_spectrum_analyzer.py, instruments/tests/test_abstract_inst/test_oscilloscope.py, instruments/tests/test_abstract_inst/test_power_supply.py
Included instruments with full tests now:
- Electrometer
- Function Generator
- Multimeter
- Optical spectrum analyzer
- Oscilloscope
- Power supply
Full test suites using pytest fixtures to patch the metaclasses such
that they become accessible, see PEP 3119.
Fixed `@abc.abstractproperty` decorators in optical spectrum analyzer
and oscilloscope, since this decorator is deprecated since py3.3.
=> Full test suite and fixes for meta-instruments in abstract instruments

instruments/tests/test_thorlabs/test_thorlabs_sc10.py, instruments/thorlabs/sc10.py
adds a space after the `>` prompt resulting in `> ` for the thorlabs sc10 shutter controller.
See discussion in #296
=> add space to prompt for TL SC10

instruments/tests/test_abstract_inst/test_signal_generator/test_channel.py, instruments/tests/test_abstract_inst/test_signal_generator/test_signal_generator.py, instruments/tests/test_abstract_inst/test_signal_generator/test_single_channel_sg.py
Same as for the other abstract classes, now for the signal generator folder in abstract_instruments
- Full coverage
- Adopt a pytest fixture to directly access abstract classes
- Test properties / methods for existence
=> Create test suite for abstract signal generator instruments

dev-requirements.txt, instruments/abstract_instruments/comm/visa_communicator.py, instruments/tests/test_comm/test_visa_communicator.py
Figured I'll take care of issue #307 and incorporate a few tests for the visa communicator. Using `pyvisa-sim` to simulate a non-connected device.
- read_raw() now uses read_raw() of pyvisa and not read() - as discussed in #307 
- Not implemented functions now raise NotImplementedError
- Removed testing if pyvisa is present
More details given with code comments. Would be great if @thestumbler could test the BF with the actual instrument present!
=> BFs for visa_communicator and tests

instruments/abstract_instruments/instrument.py, instruments/tests/test_base_instrument.py, setup.cfg
- Added tests for `open_usb` and `open_gpibethernet`
- Removed checks for modules `usb` and `pyvisa` not present since they
are now by default part of IK
=> Add tests for full coverage of instrument.py. Remove legacy checks.

doc/source/apiref/newport.rst, instruments/abstract_instruments/instrument.py, instruments/newport/__init__.py, instruments/newport/newport_pmc8742.py, instruments/tests/test_newport/test_newport_pmc8742.py
Here's a new driver for  a change (of course including the tests).
**Newport Picomotor Controller 8742**
Full functionality for this controller in single-controller and multi-controller mode (main / secondaries via RS-485) is implemented. Only single-controller mode is tested with hardware at the moment. Full test suite however includes tests for multi-controller modes. Routines were documented in docstring and also in Sphinx documentation.
Note: Control via USB is currently not functional, since InstrumentKit has some issues with the real USB communications class. I will look more into this and start an issue. Since the PMC8742 is a "true" USB device (i.e., not a serial device that is plugged into USB), this is a good class to test the USB communicator.
=> Newport picomotor controller 8742

instruments/newport/errors.py
The error codes corresponding to errors x00 to x09 are not associated to their corresponding axis due to improper matching of the error dictionary for single digit errors.
Using :02d format we force a two digit string which matches the corresponding error correctly. This does not affect other error codes.
=> Newport error codes x00 to x09 fixed

.github/workflows/test.yml
It looks like the `no-commit-to-branch` only skips if you are not on a branch, which is usually the case in CI, such as TravisCI.
However Github Actions actually does checkout the branch, which means that this hook is run post-merge in CI, which fails even if you have no changed files.
This skips that hook in CI.
=> Skip no-commit-to-branch in CI

.github/workflows/test.yml
PR moves the extra report back that coveralls was doing. Solution was found in this comment https://github.com/lemurheavy/coveralls-public/issues/1505#issuecomment-732588375
=> Fix coveralls submission

.github/workflows/test.yml, README.rst, setup.cfg, tox.ini
Closes #326
Adds Py310 support, and bumps `ruamel.yaml` to the `0.16.x` series. Looking into the docs, I see: 
>  The 0.17 series will also stop support for the old PyYAML functions, so a `YAML()` instance will need to be created.
So I'll make that a separate ticket to update calls and open up the versioning upper limit
=> Add py310 support

instruments/tests/__init__.py
This extension is useful to do unitful equality assertions while allowing the user to modify the tolerances of the approximations. Especially when dealing with instruments, such modifications can be useful.
Extended docstring to include changes.
=> Add `kwargs` to `unit_eq` and `iterable_eq`: passed on to pytest approx

instruments/tests/test_thorlabs/test_thorlabs_apt.py, instruments/thorlabs/thorlabsapt.py
For APT Motor Controllers, homing parameters can be set. This was so far not included in `ik`. Now it is, and tested (w/ pytests and with a "PRM1-Z8" stage).
Small addition to the overall monster APT driver.
=> Extend APT Motor Controller to set / get home parameters

doc/source/devguide/testing.rst
=> Add tox instructions to testing.rst

.github/workflows/test.yml, .gitignore, README.rst, tox.ini
With the move to a new `instrumentkit` org, we weren't able to bring forward all the coveralls code coverage history. And to be honest, the UI, tools, and documentation were all pretty janky. So I gave codecov a shot and it seems to be smoother sailing. We'll give that a try and see if we like it.
=> Switch to codecov

.github/workflows/test.yml
Updating my fork by merging the updated branch into it seems to run the tests now. Static checks pass, however (and of course), the actual tests fails when trying to push to codecov. 
Here, the proposed change is to check if the owner is `instrumentkit` and if so, run the tests, otherwise not. Alternatively, we probably could only make the codecov push owner dependent and keep the tests, running even on forks.
=> Add 'instrumentkit' as owner requirement to workflow

tests/test_comm/test_usb_communicator.py, tests/test_keithley/test_keithley195.py, tests/test_keithley/test_keithley580.py, tests/test_newport/test_newportesp301.py, tests/test_tektronix/test_tktds5xx.py, tests/test_thorlabs/test_thorlabs_apt.py
Hypothesis started to point out that using hypothesis.given in combination with pytest fixtures, that the fixtures don't reset in between hypothesis iterations.
This changes some of the fixtures around, or changes their scope, to remove the warnings. I believe these warnings become errors in newer versions, so this is a blocker to updating
fyi @trappitsch
=> Fix HypothesisDeprecationWarning

src/instruments/abstract_instruments/comm/loopback_communicator.py, tests/test_comm/test_loopback.py
I found a bug, that (at least under windows in cmd line and in ipython console) the loop-back without given input raises an error:
input() returns a string, while abstract_comm.read() expects an encoded byte array.
Corresponding to this change, also line 119 might be able to be deleted, as the last return will also return 118's input_var.
If you like, I could open an issue as well.
=> Ensure a correctly encoded input for manual input.

src/instruments/util_fns.py, tests/test_property_factories/test_unitful_property.py, tests/test_util_fns.py
unitful_property did compare before assume_units was called, therefore a value without a unit did not pass the comparison, but raised an exception.
Assume_units accepts strings with units as well.
=> Fixes #354 bug that unitful_property with limits fails

README.rst
Just noticed that there were some typos in the links to `pyenv` and `pre-commit`. Just a fix for the links so they work and look as intended.
=> Fix links in readme

src/instruments/abstract_instruments/comm/visa_communicator.py, tests/test_comm/test_visa_communicator.py
As lined out in #359, here are some fixes for the `pyisa` terminator.
`pyvisa` uses `read_termination` and `write_termination` props to set the respective terminators for commands ([see here](https://pyvisa.readthedocs.io/en/latest/introduction/communication.html?highlight=read_termination#getting-the-instrument-configuration-right)). This has led to issues in `ik`, which uses by default a `terminator` property to set terminator for all instruments. The `VisaCommunicator` class was extended to:
- Expose `read_termination` and `write_termination` properties to the user, which are forwarded to `pyvisa`.
- Use the `terminator` property (`ik` style) to, upon initialization of the class, set the default terminator in `pyvisa` by setting `read_termination` and `write_termination` with the same …
=> Fix terminator issues with pyvisa

src/instruments/thorlabs/sc10.py, tests/test_thorlabs/test_thorlabs_sc10.py
As discussed in #368, this PR rewrites the `sc.enable` routine for the Thorlabs SC10 shutter as a toggle. The toggle is implemented such that any setting of the property first queries the current status and then acts accordingly, i.e., toggle the status if necessary.
Tests are implemented for all cases. Existing get / set property test was split out into a get and set test. The latter now tests for cases, such that all cases are covered.
=> Rewrite SC10 shutter enable as toggle

src/instruments/gentec_eo/blu.py, tests/test_gentec_eo/test_blu.py, tests/test_keithley/test_keithley580.py
This fixes the failing tests related to updating `hypothesis`.
I didn't look too far into `test_keithley580.py::test_measure`, but increasing the threshold seemed to fix it.
For `test_blu.py::test_format_eight_length_values` `hypothesis` seems to have revealed a bug where values close to 0 with 3 digit exponents would get set to the wrong size. I simply forced those values to 0, which seems like an alright solution unless there's a need for such small values.
Also the function claims 1% error, but this is only true for positive numbers. For negative numbers, the error can be as high as 5%. I haven't done the math to figure out why this is, but I did make a plot showing near-5% error.
=> Fix hypothesis precision errors

.github/workflows/test.yml, README.rst, setup.cfg, src/instruments/gentec_eo/blu.py, tests/test_gentec_eo/test_blu.py, tests/test_keithley/test_keithley580.py, tox.ini
CI is broken right now because we're trying to use old versions of pytest and hypothesis and they're not working with some other packages that have since udpated.
This PR updates pytest and hypothesis, fixes any test issues that surfaced, and drops Py36 support.
Why drop Py36 support here? Well because these updated packages don't support Py36 since it is now past end-of-life.
=> Bump pytest 7.2.0, hypothesis 6.56.0

.github/workflows/test.yml, README.rst, setup.cfg, tox.ini
CPython 3.11 is out, see https://www.python.org/downloads/release/python-3110/
Local tests seem to all run well, this PR adds support for 3.11.
=> Add support for CPython 3.11

src/instruments/yokogawa/yokogawa6370.py, tests/test_yokogawa/test_yokogawa_6370.py
As discussed in #386, when connecting via TCP IP, the Yokogawa 6370 terminator is fixed to `"\r\n"`. This is now automatically set in the instrument when this type of connection is established.
=> BF Yokogawa 6370, terminator setup for TCPIP

doc/source/apiref/index.rst, doc/source/apiref/mettler_toledo.rst, src/instruments/__init__.py, src/instruments/mettler_toledo/__init__.py, src/instruments/mettler_toledo/mt_sics.py, tests/test_mettler_toledo/test_mt_sics.py
Provide support for Mettler Toledo balances via their Standard Interface Communication Software. 
For manual, see [here](https://www.mt.com/ch/en/home/library/user-manuals/laboratory-weighing/RM-MT-SICS-MS-ML-ME.html).
This is a start of a new class for MT balances. Not all advanced functions are included, however, should be useful for the standard user that just needs to automate some weighting.
=> Mettler Toledo Standard Interface Communication Software

setup.cfg
As discussed in #395, pinning the pint version to `>=0.16.1,<0.21.0`. This should fix the current testing issue, but needs revisiting when we drop `py37` support.
=> Pin pint to >=0.16.1,<0.21.0

src/instruments/abstract_instruments/comm/socket_communicator.py, src/instruments/abstract_instruments/instrument.py, src/instruments/yokogawa/yokogawa6370.py, tests/test_base_instrument.py, tests/test_yokogawa/test_yokogawa_6370.py
This was first mentioned in #386. The Yokogawa 6370 authentication via TCPIP can go with username, password, or with anonymous user identification, where the username `anonymous` is sent and any password is valid.
I added a private `_authenticate` routine to `instrument` and to the Yokogawa itself (where it is actually implemented). The authentication will likely be slightly different for different instruments, therefore it is specific to the instrument.
@slagroommarino it would be great if you can test this with the actual instrument!
The one thing that might be iffy: the password authentication is in plain text. While the instrument accepts MD5 hashing, the way it would have to be implemented requires user interaction, see [manual](https://cdn.tmi.yokogawa.com/1/6057/files/IMAQ6370C-17EN …
=> Add functionality to authenticate via TCPIP

.github/workflows/test.yml, README.rst, setup.cfg, tests/test_newport/test_newportesp301.py, tox.ini
Add support and testing for py3.12, drop 3.7 since EOL. Change a test to `assert_has_calls`, since `has_calls` seems to be depreciated in 3.12.
Note: There are a few more depreciation warnings that need to be taken care of. However, this should be fixed in a separate PR.
=> CPython 3.12 support, drop 3.7

setup.cfg, src/instruments/units.py
Upgrade `pint` dependency to remove the in-between pinning we had previously.
Percent does not have to be specifically defined anymore, since it is supported since `v0.21`.
See discussion in #406
=> Updgrade pint dependency

.github/workflows/test.yml
Switch actions to newer versions to avoid issues in the future (when older versions get dropped)
- Checout action `v4`
- Setup-python action `v5`
- Codecov action `v4`
Double checked all variables that are set in codecov upload - they are correct. Moving up to action v4, let's see if the upload works. I'm assuming the secret is set :)
=> Upgrade test workflow to use newer versions of actions

setup.cfg, src/instruments/config.py, tests/test_config.py
Part of #406 
- Fix configuration to use the new style
- Fix test where old loader was called
Currently I'm using the `unsafe` loader, which would be okay since the docs specify that this is not safe for files you don't trust. 
However, we could try and register all `ik` classes with the yaml loader, [see here](https://yaml.readthedocs.io/en/latest/dumpcls/). Scratching my head at the moment though why I can't even get the tests to run when I register `instruments.Instrument` with 
```python
from instruments.config import yaml
@yaml.register_class
class Instrument
...
```
Any ideas?
=> Update ruamel.yaml to >=0.18

setup.cfg
Ok, last one for #406:
Updating `pytest` and `hypothesis` to the latest versions. Also added a missing `__init__.py` file, which `pytest` complained about is missing due to the change in `8.0.0` of test collection.
As discussed in #406, these dependencies are still pinned to minor versions, however, to new ones. Should keep us future proof for a while longer.
Looks like all passing and good. Closes #406
=> Update dev dependencies

src/instruments/mettler_toledo/mt_sics.py
If you attempt to call open_tcpip with the mettler_toledo module, it will fail with an unexpected keyword argument error. This adds *args, **kwargs to __init__ and passes them to super.
=> Rework Mettler Toledo init to allow for tcpip connection

doc/source/apiref/dressler.rst, doc/source/apiref/index.rst, src/instruments/__init__.py, src/instruments/abstract_instruments/comm/serial_manager.py, src/instruments/abstract_instruments/instrument.py, src/instruments/dressler/__init__.py, src/instruments/dressler/cesar_1312.py, tests/test_dressler/test_cesar_1312.py
Here's support for the Dressler Cesar 1312 RF generator. An older instrument, but works great via RS232. The most important commands are implemented and especially the package sending/receiving are working very well. Functionality that is covered:
- Select control mode 
- Select regulation mode
- Set/get the output power
- Read back reflected power
- Turn on/off RF and read status
Test coverage included, added to docs.
Curious to hear your opinion @scasagrande. There is no dedicated RF generator, so inheriting from Instruments. Might be something to think about...
=> Dressler Cesar 1312 RF generator

doc/source/apiref/comet.rst, doc/source/apiref/index.rst, src/instruments/__init__.py, src/instruments/comet/__init__.py, src/instruments/comet/cito_plus_1310.py, tests/test_comet/test_cito_plus_1310.py
This PR adds support for the [Comet Cito Plus 1310 RF generator](https://pct.comet.tech/en/products/rf-generators/cito-plus). It includes:
- Instrument support for the most common / important commands (probably fairly subjective), which includes a command builder and instrument querying
- Test suite
- Docs and examples (API)
Likely, this should also work for the regular Cito 1310 generator and others.
Incorporating additional commands should be simple by following the laid out structure.
=> Comet cito plus 1310 RF generator

src/instruments/abstract_instruments/instrument.py, src/instruments/comet/cito_plus_1310.py, src/instruments/dressler/cesar_1312.py
I noticed a few things that I didn't do cleanly in these classes, so here are a couple of fixes. This corrects typos in the docstring, but also the following:
Non standard parities for the serial communication is used in these devices. So far I set this in the `__init__` of the class, however, I rapidly noticed that this is a terrible idea as it limits the driver to be only via RS232. Connecting the instrument via, e.g., an RS232 to ethernet converter (i.e., using a MOXA) would not work and throw an error. So here's a fix for that:
- Remove the call to serial in the initialization
- Rather allow user additional `**kwargs` when opening serial and pass these optional ones to creating the serial communicator. This allows to set `parity`, etc.
- Document this better in the drivers, plus in …
=> Bug fixes for Comet and Dressler RF generator

setup.cfg
https://github.com/instrumentkit/InstrumentKit/issues/429
Addresses `python-pyvxi11` dependency on system package `xdrlib`, which has been removed in Py3.13
=> Depend on standard-xdrlib if >= Py 3.13

src/instruments/abstract_instruments/comm/abstract_comm.py
I've been working on this as well, thus a creative PR for a change ;) 
Here's a fix for the last of your py3.13 issues (after this, it's only a bunch of warnings).
The tests that fail without this are the ones that fail out of the class before a connection is built up. I think when throwing the error, as no `self._conn` exists, no `self.address` can exist and an error is thrown (but not the correct one we are testing for) when python tries to print the error message. Well, this is my feeling, I have not really gone deep enough down the rabbit hole to find any of this behavior in the changelog for py3.13...
=> Change __repr__ of abstract communicator to be always representable

src/instruments/abstract_instruments/instrument.py, src/instruments/yokogawa/yokogawa6370.py, tests/test_base_instrument.py
This fixes the bug discussed in #439 and adds a test that fails because of this issue.
Now, the variable `auth` in `.open_tcpip` classmethod is only passed on to the instrument class itself it is not `None`, which is the default value. 
I also corrected the initialization of the Yokogawa 6370. This one is now consistent with the rest of the instruments and does not accept `args`, `kwargs` anymore, but still does accept `auth`. All tests for the Yokogawa 6370 still pass.
*Note*: I will double check this as well with an actual instrument that has failed so far due to this error and confirm that it works now (assuming it does).
Closes #439
=> Fix the open_tcpip bug that crept in with the `auth` argument

doc/source/apiref/index.rst, doc/source/apiref/pfeiffer.rst, src/instruments/__init__.py, src/instruments/pfeiffer/__init__.py, src/instruments/pfeiffer/tpg36x.py, tests/test_pfeiffer/test_tpg36x.py
This PR adds support for the Pfeiffer TPG36x single or dual channel vaccuum gauge controller. 
Instrument communications mainly implemented by @Mathias-koller, I added some test and cleanup.
Tested with a dual gauge controller in lab.
=> Add support Pfeiffer TPG36x Vaccuum Gauge Controller

doc/source/apiref/index.rst, doc/source/apiref/sunpower.rst, src/instruments/__init__.py, src/instruments/sunpower/__init__.py, src/instruments/sunpower/cryotel_gt.py, tests/test_sunpower/test_cryotel_gt.py
This PR adds support for the Sunpower/Ametek CryoTel GT cryocooler. The generation 2 driver was used, which works for devices purchased after May 2012. This is also noted in the driver itself.
Added tests for full coverage and tested extensively in lab. 
Error code handling: Currently returns a list of human readable strings that is calculated from the return using a bitmask... maybe not the most fancy way of doing it.
As always, let me know what you think!
=> Add support for sunpower cryotel gt gen2

doc/source/apiref/lakeshore.rst, src/instruments/abstract_instruments/comm/serial_manager.py, src/instruments/lakeshore/__init__.py, src/instruments/lakeshore/lakeshore336.py, tests/test_lakeshore/test_lakeshore336.py
Heavily copied from Lakeshore340 class and provides the same functionality for the Model 336. Communications seem different as well as channel addressing. 
At the moment, there's only reading the temperatures of the four input channels implemented and no other functionality (reason: that's really all I need for now). 
One thing: since this device requires odd parity and bitsize 7, these arguments are now forwarded as `**kwargs` to the serial manager and from there to `pyserial` when opening the connection.
LMK if you have a wishlist for further commands to be implemented or if somebody has a whish. As the device is here, I'd be happy to implement and test further if need be :) Figured I submit this in a barebones state as it initializes the comms and can also serve as a base for future …
=> Minimal support for Lakeshore Model 336 cryogenic temperature controller

README.rst
Update to the readme for the latest changes, also adds how to install the latest pre-release from pypi.
=> update readme for latests changes in installation
